### ISSUE TITLE
Commit from October 17 2018 not available in 3.1.0-RC1

### ISSUE THREAD

**Issue by theiosdevguy** [grails-plugins/grails-spring-security-oauth2-provider#6]
### Commit from October 17 2018 not available in 3.1.0-RC1

I am getting "No such property: log for class: grails.plugin.springsecurity.oauthprovider.GormTokenStoreService" error when hitting oauth/token api. Looking at the code for GormTokenStoreService, it looks like the commit made for this fix on October 17 is not available in release 3.1.0-RC1. Please provide a fix for this or an alternative route.

**Comment by theiosdevguy** [comment]
Looking at the release dates, it looks like 3.1.0-RC1 was released on October 13, 2018 and the bug fixes on October 17, 2018. Could you please create a new release?

**Comment by puneetbehl** [comment]
@theiosdevguy I am working on testing the plugin, found some issues and will try to close it by this week.

**Comment by bluesliverx** [comment]
@theiosdevguy finally had some time over the holiday to get this released the right way - 3.2.1 should now be released (https://bintray.com/bluesliverx/grails-plugins/spring-security-oauth2-provider)
